Repository youngminss/modu-memu-client, pull requests merged in 2024-01, with the labels that each got.

#11 자식 컴포넌트를 중앙 정렬시키는 부모 컴포넌트 생성
  app/layout.tsx
  app/map/layout.tsx
  app/map/page.tsx
  legacy/IconTitleList.tsx
  legacy/KakaoMap.tsx
  legacy/app/Layout.tsx
  legacy/app/MapPage.tsx
  legacy/src/MapPage.tsx
  legacy/useGeolocationPosition.ts
  public/images/logo.png
  public/images/logo.svg
  src/components/Header.tsx
  src/components/KakaoMap.tsx
  src/components/Layout.tsx
  src/components/common/Header.tsx
  src/components/home/IconTileList.tsx
  src/pages/home/page.tsx
  src/pages/map/page.tsx
  src/store/useGeolocationPosition.ts
  src/utils/functions/storage.ts
Labels: UI, 민철, 리뷰요청

#13 위치 검색받는 UI 컴포넌트
  public/images/search-location.svg
  public/images/search.svg
  src/components/SearchLocation.tsx
  src/pages/home/page.tsx
  tailwind.config.ts
Labels: UI, 민철

#14 주소 입력 창
  package.json
  src/components/InputPostCode.tsx
  src/components/SearchLocation.tsx
  yarn.lock
Labels: 영민, UI, 기능

#12 [통합용] 기본 레이아웃 및 주소 입력창 작업
  app/layout.tsx
  app/map/layout.tsx
  app/map/page.tsx
  legacy/IconTitleList.tsx
  legacy/KakaoMap.tsx
  legacy/app/Layout.tsx
  legacy/app/MapPage.tsx
  legacy/src/MapPage.tsx
  legacy/useGeolocationPosition.ts
  package.json
  public/images/logo.png
  public/images/logo.svg
  src/components/Header.tsx
  src/components/InputPostCode.tsx
  src/components/KakaoMap.tsx
  src/components/Layout.tsx
  src/components/SearchLocation.tsx
  src/components/common/Header.tsx
  src/components/home/IconTileList.tsx
  src/pages/home/page.tsx
  src/pages/map/page.tsx
  src/store/useGeolocationPosition.ts
  src/utils/functions/storage.ts
  tailwind.config.ts
  yarn.lock
Labels: 통합용

#15 Stage to main
  app/layout.tsx
  app/map/layout.tsx
  app/map/page.tsx
  legacy/IconTitleList.tsx
  legacy/KakaoMap.tsx
  legacy/app/Layout.tsx
  legacy/app/MapPage.tsx
  legacy/src/MapPage.tsx
  legacy/useGeolocationPosition.ts
  package.json
  public/images/logo.png
  public/images/logo.svg
  src/components/Header.tsx
  src/components/InputPostCode.tsx
  src/components/KakaoMap.tsx
  src/components/Layout.tsx
  src/components/SearchLocation.tsx
  src/components/common/Header.tsx
  src/components/home/IconTileList.tsx
  src/pages/home/page.tsx
  src/pages/map/page.tsx
  src/store/useGeolocationPosition.ts
  src/utils/functions/storage.ts
  tailwind.config.ts
  yarn.lock
Labels: 통합용
